[package]
name = "c4-rust-2"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = "0.4"
rand = "0.8"
minifb = "0.19"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

