[package]
name = "ppo-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = "0.4"
rand = { version = "0.8.5", features = [ "small_rng" ] }
ggez = "0.5"
nalgebra = "0.29"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

